#!/usr/bin/env python3
"""Export, transform, validate, and optionally deploy a Clash Verge config for OpenClash.

The transformation is deterministic and idempotent:

- Preserve all static nodes (proxies), specialist groups, DNS, and rules.
- Add global manual/automatic groups with regional failover via priority wrappers.
- Add GPT, Gemini, and Disney specialist groups with regional failover.
- Gemini explicitly excludes United States nodes.
- Each selectable node gets a "优先│<node>" fallback wrapper that
  automatically falls back to the corresponding auto group on health-check failure.
- The final MATCH rule routes to the default manual group.

The script never prints proxy credentials or the full YAML body.
"""

from __future__ import annotations

import argparse
import datetime as dt
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Iterable

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "Missing dependency: PyYAML. Install with: python3 -m pip install PyYAML"
    ) from exc


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_VERGE_CANDIDATES = (
    Path.home()
    / "Library/Application Support/io.github.clash-verge-rev.clash-verge-rev/clash-verge.yaml",
    Path.home()
    / "Library/Application Support/com.github.clash-verge-rev.clash-verge-rev/clash-verge.yaml",
)

FALLBACK_URL = "https://www.gstatic.com/generate_204"
FALLBACK_INTERVAL = 60
FALLBACK_TIMEOUT = 5000
FALLBACK_MAX_FAILED = 1

# Skill-generated group names that must be removed on re-generation.
SKILL_GROUP_NAMES: set[str] = {
    "默认代理",
    "手动选择",
    "自动选择",
    "GPT专用",
    "GPT手动",
    "GPT自动",
    "Gemini专用",
    "Gemini手动",
    "Gemini自动",
    "迪士尼",
    "迪士尼手动",
    "迪士尼自动",
}

# Prefixes for wrapper groups generated by this skill.
SKILL_WRAPPER_PREFIXES = ("全局优先│", "GPT优先│", "Gemini优先│", "迪士尼优先│")

# Region keywords – Chinese names and common flag emoji.
REGION_KEYWORDS: dict[str, list[str]] = {
    "日本": ["日本", "\U0001f1ef\U0001f1f5"],  # 🇯🇵
    "台湾": ["台湾", "\U0001f1f9\U0001f1fc"],  # 🇹🇼
    "香港": ["香港", "\U0001f1ed\U0001f1f0"],  # 🇭🇰
    "德国": ["德国", "\U0001f1e9\U0001f1ea"],  # 🇩🇪
    "美国": ["美国", "\U0001f1fa\U0001f1f8"],  # 🇺🇸  – exclusion only
}

# Region display-name → sort key for global / GPT / Disney.
_GLOBAL_REGION_ORDER = {"日本": 0, "台湾": 1}
# Region display-name → sort key for Gemini.
_GEMINI_REGION_ORDER = {"日本": 0, "台湾": 1, "香港": 2, "德国": 3}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


class ConfigError(RuntimeError):
    """Raised when the source configuration cannot be transformed safely."""


def now_stamp() -> str:
    return dt.datetime.now().strftime("%Y%m%d-%H%M%S")


def run(cmd: list[str], *, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        check=check,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )


def find_default_source() -> Path:
    for candidate in DEFAULT_VERGE_CANDIDATES:
        if candidate.is_file():
            return candidate

    base = Path.home() / "Library/Application Support"
    matches = sorted(base.glob("*clash-verge*/**/clash-verge.yaml")) if base.exists() else []
    for match in matches:
        if match.is_file():
            return match

    searched = "\n".join(f"  - {p}" for p in DEFAULT_VERGE_CANDIDATES)
    raise ConfigError(
        "Could not find the Clash Verge effective configuration. Checked:\n"
        f"{searched}\nPass --source explicitly."
    )


def load_yaml(path: Path) -> dict[str, Any]:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise ConfigError(f"Cannot read source file: {path}: {exc}") from exc
    except yaml.YAMLError as exc:
        raise ConfigError(f"Invalid YAML in {path}: {exc}") from exc

    if not isinstance(data, dict):
        raise ConfigError("The YAML root must be a mapping/object.")
    return data


def dump_yaml(data: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = yaml.safe_dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=4096,
    )
    path.write_text(text, encoding="utf-8")


def ordered_unique(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value not in seen:
            result.append(value)
            seen.add(value)
    return result


# ---------------------------------------------------------------------------
# Node helpers
# ---------------------------------------------------------------------------


def static_node_names(data: dict[str, Any]) -> list[str]:
    proxies = data.get("proxies")
    if not isinstance(proxies, list) or not proxies:
        raise ConfigError(
            "No static nodes were found under 'proxies:'. Export the Clash Verge effective/merged "
            "configuration rather than a provider-only subscription."
        )

    names: list[str] = []
    for index, proxy in enumerate(proxies):
        if not isinstance(proxy, dict):
            raise ConfigError(f"proxies[{index}] is not an object.")
        name = proxy.get("name")
        if not isinstance(name, str) or not name.strip():
            raise ConfigError(f"proxies[{index}] has no valid name.")
        names.append(name)

    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise ConfigError(f"Duplicate proxy names detected: {', '.join(duplicates)}")
    return names


def detect_region(name: str) -> str | None:
    """Return the canonical region display-name if *name* contains a region keyword."""
    name_lower = name.casefold()
    for region, keywords in REGION_KEYWORDS.items():
        for kw in keywords:
            if kw.casefold() in name_lower:
                return region
    return None


def region_sort_key(name: str, order: dict[str, int]) -> tuple[int, int]:
    """Sort tuple: (region_rank, 0) for recognised regions, (9999, 1) for others."""
    region = detect_region(name)
    if region and region in order:
        return (order[region], 0)
    return (9999, 1)


def _region_order_global_tw_others(name: str) -> tuple[int, int]:
    return region_sort_key(name, _GLOBAL_REGION_ORDER)


def _region_order_gemini(name: str) -> tuple[int, int]:
    return region_sort_key(name, _GEMINI_REGION_ORDER)


def is_skill_group(name: str) -> bool:
    """Return True if *name* is a group generated by this skill."""
    if name in SKILL_GROUP_NAMES:
        return True
    for prefix in SKILL_WRAPPER_PREFIXES:
        if name.startswith(prefix):
            return True
    return False


def is_priority_wrapper(name: str) -> bool:
    """Return True if *name* matches any skill wrapper prefix."""
    return any(name.startswith(p) for p in SKILL_WRAPPER_PREFIXES)


# ---------------------------------------------------------------------------
# Candidate extraction
# ---------------------------------------------------------------------------


def _static_proxies_in_group(
    groups: list[dict[str, Any]], group_name: str, node_names: set[str]
) -> list[str]:
    """Return proxy names in *group_name* that are static nodes."""
    for g in groups:
        if g.get("name") == group_name:
            proxies = g.get("proxies")
            if isinstance(proxies, list):
                return ordered_unique(p for p in proxies if p in node_names)
    return []


def extract_gpt_candidates(
    groups: list[dict[str, Any]], node_names: set[str]
) -> list[str]:
    """GPT candidates from GPT专用 → fallback GPT自动."""
    candidates = _static_proxies_in_group(groups, "GPT专用", node_names)
    if not candidates:
        candidates = _static_proxies_in_group(groups, "GPT自动", node_names)
    return candidates


def extract_gemini_candidates(
    groups: list[dict[str, Any]], node_names: set[str]
) -> list[str]:
    """Gemini candidates: region-filtered (Japan, Taiwan, Hong Kong, Germany, exclude US)."""
    candidates = _static_proxies_in_group(groups, "Gemini专用", node_names)
    if not candidates:
        candidates = _static_proxies_in_group(groups, "Gemini自动", node_names)
    if not candidates:
        candidates = list(node_names)

    allowed_regions = {"日本", "台湾", "香港", "德国"}
    return ordered_unique(
        n for n in candidates if detect_region(n) in allowed_regions
    )


def extract_disney_candidates(
    groups: list[dict[str, Any]],
    node_names: set[str],
    media_keywords: list[str],
) -> list[str]:
    """Disney candidates: original group static nodes + keyword-matched nodes."""
    candidates = _static_proxies_in_group(groups, "迪士尼", node_names)
    if not candidates:
        candidates = _static_proxies_in_group(groups, "迪士尼自动", node_names)

    matched = [
        name
        for name in node_names
        if any(keyword.casefold() in name.casefold() for keyword in media_keywords)
    ]
    result = ordered_unique(list(candidates) + matched)
    return result


# ---------------------------------------------------------------------------
# Group building
# ---------------------------------------------------------------------------


def build_fallback_group(
    name: str,
    proxies: list[str],
    *,
    url: str = FALLBACK_URL,
    interval: int = FALLBACK_INTERVAL,
    timeout: int = FALLBACK_TIMEOUT,
    max_failed_times: int = FALLBACK_MAX_FAILED,
) -> dict[str, Any]:
    return {
        "name": name,
        "type": "fallback",
        "proxies": proxies,
        "url": url,
        "interval": interval,
        "lazy": True,
        "timeout": timeout,
        "max-failed-times": max_failed_times,
    }


def build_select_group(name: str, proxies: list[str]) -> dict[str, Any]:
    return {"name": name, "type": "select", "proxies": proxies}


def build_priority_wrappers(
    nodes: list[str],
    prefix: str,
    auto_group: str,
) -> list[dict[str, Any]]:
    """Build per-node fallback wrappers: ``{prefix}{node}`` → [node, auto_group]."""
    wrappers: list[dict[str, Any]] = []
    for node in nodes:
        wrapper_name = f"{prefix}{node}"
        wrappers.append(
            build_fallback_group(wrapper_name, [node, auto_group])
        )
    return wrappers


# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------


def remove_skill_groups(groups: list[dict[str, Any]]) -> None:
    """Remove every group that matches a skill-generated name or prefix."""
    to_remove = [i for i, g in enumerate(groups) if is_skill_group(g.get("name", ""))]
    for i in reversed(to_remove):
        del groups[i]


def remove_old_match_rules(data: dict[str, Any]) -> None:
    """Delete all existing MATCH rules."""
    rules = data.get("rules", [])
    if not isinstance(rules, list):
        raise ConfigError("'rules' must be a list.")
    data["rules"] = [
        r for r in rules if not (isinstance(r, str) and r.strip().upper().startswith("MATCH,"))
    ]


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate_references(data: dict[str, Any], node_names: list[str]) -> None:
    groups = data.get("proxy-groups", [])
    group_names = {
        item.get("name")
        for item in groups
        if isinstance(item, dict) and isinstance(item.get("name"), str)
    }
    valid_targets = set(node_names) | group_names | {"DIRECT", "REJECT", "REJECT-DROP", "PASS"}

    errors: list[str] = []
    for group in groups:
        name = group.get("name", "<unnamed>")
        refs = group.get("proxies", [])
        if refs is None:
            continue
        if not isinstance(refs, list):
            errors.append(f"group '{name}' has a non-list proxies field")
            continue
        for ref in refs:
            if isinstance(ref, str) and ref not in valid_targets:
                errors.append(f"group '{name}' references missing target '{ref}'")

    if errors:
        raise ConfigError("Reference validation failed:\n- " + "\n- ".join(errors))


def check_cycles(groups: list[dict[str, Any]]) -> None:
    """Detect self-references and simple cycles in proxy-groups."""
    group_map: dict[str, list[str]] = {}
    for g in groups:
        name = g.get("name", "")
        refs = g.get("proxies", [])
        if isinstance(name, str) and isinstance(refs, list):
            group_map[name] = [r for r in refs if isinstance(r, str)]

    errors: list[str] = []

    # Self-reference
    for gname, refs in group_map.items():
        if gname in refs:
            errors.append(f"group '{gname}' references itself")

    # Simple two-step cycle
    for gname, refs in group_map.items():
        for r in refs:
            if r in group_map and gname in group_map[r] and gname != r:
                errors.append(f"cycle detected: '{gname}' ↔ '{r}'")

    if errors:
        raise ConfigError("Cycle validation failed:\n- " + "\n- ".join(errors))


def check_unique_group_names(groups: list[dict[str, Any]]) -> None:
    names = [g.get("name", "") for g in groups]
    duplicates = sorted({n for n in names if names.count(n) > 1})
    if duplicates:
        raise ConfigError(f"Duplicate group names: {', '.join(duplicates)}")


# ---------------------------------------------------------------------------
# Main transform
# ---------------------------------------------------------------------------


def transform(
    data: dict[str, Any],
    *,
    manual_group: str,
    auto_group: str,
    disney_group: str,
    media_keywords: list[str],
    test_url: str = FALLBACK_URL,
    interval: int = FALLBACK_INTERVAL,
    tolerance: int | None = None,
) -> dict[str, Any]:
    node_names = static_node_names(data)
    node_set = set(node_names)
    groups = data.setdefault("proxy-groups", [])
    if not isinstance(groups, list):
        raise ConfigError("'proxy-groups' must be a list.")
    for index, item in enumerate(groups):
        if not isinstance(item, dict):
            raise ConfigError(f"proxy-groups[{index}] is not an object.")

    # --- Extract candidates from existing groups (before cleanup) ---
    global_nodes = node_names  # all static nodes
    gpt_nodes = extract_gpt_candidates(groups, node_set)
    gemini_nodes = extract_gemini_candidates(groups, node_set)
    disney_nodes = extract_disney_candidates(groups, node_set, media_keywords)

    # Sort every candidate list deterministically so wrappers and auto groups
    # follow the same order, guaranteeing idempotency on re-processing.
    global_nodes_sorted = sorted(global_nodes, key=_region_order_global_tw_others)
    gpt_nodes_sorted = sorted(gpt_nodes, key=_region_order_global_tw_others) if gpt_nodes else []
    gemini_nodes_sorted = sorted(gemini_nodes, key=_region_order_gemini) if gemini_nodes else []
    disney_nodes_sorted = sorted(disney_nodes, key=_region_order_global_tw_others) if disney_nodes else []

    # --- Remove old skill groups ---
    remove_skill_groups(groups)
    remove_old_match_rules(data)

    # --- Build groups ---
    # Global (always)
    fallback_url = test_url if test_url != FALLBACK_URL else FALLBACK_URL

    global_auto = build_fallback_group(
        auto_group,
        global_nodes_sorted,
        url=fallback_url,
        interval=interval,
    )
    global_wrappers = build_priority_wrappers(global_nodes_sorted, "全局优先│", auto_group)
    manual = build_select_group(
        manual_group,
        [auto_group] + [w["name"] for w in global_wrappers],
    )
    default = build_select_group(
        "默认代理",
        [manual_group, auto_group],
    )

    new_groups: list[dict[str, Any]] = [default, manual, global_auto]
    new_groups.extend(global_wrappers)

    # --- GPT groups (only if candidates exist) ---
    gpt_wrappers: list[dict[str, Any]] = []
    if gpt_nodes_sorted:
        gpt_auto = build_fallback_group(
            "GPT自动",
            gpt_nodes_sorted,
            url=fallback_url,
            interval=interval,
        )
        gpt_wrappers = build_priority_wrappers(gpt_nodes_sorted, "GPT优先│", "GPT自动")
        gpt_manual = build_select_group(
            "GPT手动",
            ["GPT自动"] + [w["name"] for w in gpt_wrappers],
        )
        gpt_special = build_select_group(
            "GPT专用",
            ["GPT手动", "GPT自动"],
        )
        new_groups.extend([gpt_special, gpt_manual, gpt_auto])
        new_groups.extend(gpt_wrappers)

    # --- Gemini groups (only if candidates exist) ---
    gemini_wrappers: list[dict[str, Any]] = []
    if gemini_nodes_sorted:
        gemini_auto = build_fallback_group(
            "Gemini自动",
            gemini_nodes_sorted,
            url=fallback_url,
            interval=interval,
        )
        gemini_wrappers = build_priority_wrappers(gemini_nodes_sorted, "Gemini优先│", "Gemini自动")
        gemini_manual = build_select_group(
            "Gemini手动",
            ["Gemini自动"] + [w["name"] for w in gemini_wrappers],
        )
        gemini_special = build_select_group(
            "Gemini专用",
            ["Gemini手动", "Gemini自动"],
        )
        new_groups.extend([gemini_special, gemini_manual, gemini_auto])
        new_groups.extend(gemini_wrappers)

    # --- Disney groups (always generate if there are candidates) ---
    disney_wrappers: list[dict[str, Any]] = []
    if disney_nodes_sorted:
        disney_auto = build_fallback_group(
            "迪士尼自动",
            disney_nodes_sorted,
            url=fallback_url,
            interval=interval,
        )
        disney_wrappers = build_priority_wrappers(disney_nodes_sorted, "迪士尼优先│", "迪士尼自动")
        disney_manual = build_select_group(
            "迪士尼手动",
            ["迪士尼自动"] + [w["name"] for w in disney_wrappers],
        )
        disney_special = build_select_group(
            "迪士尼",
            ["迪士尼手动", "迪士尼自动"],
        )
        new_groups.extend([disney_special, disney_manual, disney_auto])
        new_groups.extend(disney_wrappers)

    # --- Replace groups ---
    data["proxy-groups"] = new_groups

    # --- Final MATCH ---
    rules = data.setdefault("rules", [])
    if not isinstance(rules, list):
        raise ConfigError("'rules' must be a list.")
    rules.append("MATCH,默认代理")

    # --- Validate ---
    all_node_names = node_names
    validate_references(data, all_node_names)
    check_cycles(data["proxy-groups"])
    check_unique_group_names(data["proxy-groups"])

    return data


# ---------------------------------------------------------------------------
# Export / Deploy
# ---------------------------------------------------------------------------


def export_source(source: Path | None, workdir: Path) -> Path:
    source = source or find_default_source()
    if not source.is_file():
        raise ConfigError(f"Source does not exist: {source}")
    workdir.mkdir(parents=True, exist_ok=True)
    destination = workdir / f"clash-verge-effective-{now_stamp()}.yaml"
    shutil.copy2(source, destination)
    return destination


def quote_remote(path: str) -> str:
    return shlex.quote(path)


def ssh_command(host: str, command: str, *, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return run(["ssh", host, command], capture=capture)


def deploy(
    local_file: Path,
    *,
    host: str,
    remote_name: str | None,
    core_path: str,
    activate: bool,
) -> str:
    if not local_file.is_file():
        raise ConfigError(f"Output file does not exist: {local_file}")

    filename = remote_name or local_file.name
    if "/" in filename or filename in {".", ".."}:
        raise ConfigError("--remote-name must be a plain filename.")

    remote_dir = "/etc/openclash/config"
    remote_path = f"{remote_dir}/{filename}"
    stamp = now_stamp()
    remote_backup = f"{remote_path}.bak.{stamp}"
    remote_tmp = f"/tmp/{filename}.upload.{stamp}"

    ssh_command(
        host,
        "set -e; "
        f"mkdir -p {quote_remote(remote_dir)}; "
        f"if [ -f {quote_remote(remote_path)} ]; then cp -p {quote_remote(remote_path)} {quote_remote(remote_backup)}; fi",
    )

    run(["scp", "-O", str(local_file), f"{host}:{remote_tmp}"])

    test_cmd = (
        "set -e; "
        f"chmod 600 {quote_remote(remote_tmp)}; "
        f"{quote_remote(core_path)} -t -d /etc/openclash -f {quote_remote(remote_tmp)}; "
        f"mv -f {quote_remote(remote_tmp)} {quote_remote(remote_path)}; "
        f"chmod 600 {quote_remote(remote_path)}"
    )
    try:
        ssh_command(host, test_cmd)
    except subprocess.CalledProcessError as exc:
        ssh_command(host, f"rm -f {quote_remote(remote_tmp)}", capture=True)
        raise ConfigError("Remote Mihomo validation failed; the active configuration was not changed.") from exc

    if activate:
        activate_cmd = (
            "set -e; "
            "cp -p /etc/config/openclash "
            f"/etc/config/openclash.bak.{stamp}; "
            f"uci set openclash.config.config_path={quote_remote(remote_path)}; "
            "uci set openclash.config.enable='1'; "
            "uci commit openclash; "
            "/etc/init.d/openclash restart"
        )
        ssh_command(host, activate_cmd)

    return remote_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert a Clash Verge effective YAML into a static OpenClash configuration."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    export_p = sub.add_parser("export", help="Copy the current Clash Verge effective YAML to a work directory.")
    export_p.add_argument("--source", type=Path)
    export_p.add_argument("--workdir", type=Path, default=Path.home() / "Desktop/openclash-static-work")

    transform_p = sub.add_parser("transform", help="Transform an exported/effective YAML.")
    transform_p.add_argument("--input", type=Path, required=True)
    transform_p.add_argument("--output", type=Path, required=True)
    add_transform_args(transform_p)

    all_p = sub.add_parser("all", help="Export, transform, and optionally deploy in one command.")
    all_p.add_argument("--source", type=Path)
    all_p.add_argument("--workdir", type=Path, default=Path.home() / "Desktop/openclash-static-work")
    all_p.add_argument("--output-name", default="clash-verge-static-openclash.yaml")
    add_transform_args(all_p)
    add_deploy_args(all_p)

    deploy_p = sub.add_parser("deploy", help="Upload an existing YAML and validate it remotely before installation.")
    deploy_p.add_argument("--file", type=Path, required=True)
    add_deploy_args(deploy_p)

    dry_run_p = sub.add_parser("dry-run", help="Transform without writing output, deploying, or SSH.")
    dry_run_p.add_argument("--input", type=Path, required=True)
    add_transform_args(dry_run_p)

    return parser


def add_transform_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--manual-group", default="手动选择")
    parser.add_argument("--auto-group", default="自动选择")
    parser.add_argument("--disney-group", default="迪士尼")
    parser.add_argument(
        "--media-keyword",
        action="append",
        dest="media_keywords",
        help="Node-name keyword added to the Disney group. Repeatable. Defaults: 流媒体, 媒体流.",
    )
    parser.add_argument("--test-url", default=FALLBACK_URL)
    parser.add_argument("--interval", type=int, default=FALLBACK_INTERVAL)
    parser.add_argument("--tolerance", type=int, default=None)


def add_deploy_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--deploy", action="store_true", help="For 'all': upload after transformation.")
    parser.add_argument("--host", default="root@192.168.10.1")
    parser.add_argument("--remote-name")
    parser.add_argument("--core-path", default="/etc/openclash/core/clash_meta")
    parser.add_argument(
        "--activate",
        action="store_true",
        help="After remote validation, select this config through UCI and restart OpenClash. Opt-in only.",
    )


def transform_file(args: argparse.Namespace, input_path: Path, output_path: Path) -> dict[str, Any]:
    data = load_yaml(input_path)
    keywords = args.media_keywords or ["流媒体", "媒体流"]
    transformed = transform(
        data,
        manual_group=args.manual_group,
        auto_group=args.auto_group,
        disney_group=args.disney_group,
        media_keywords=keywords,
        test_url=args.test_url,
        interval=args.interval,
        tolerance=args.tolerance,
    )
    dump_yaml(transformed, output_path)
    return transformed


def print_summary(data: dict[str, Any], output: Path, args: argparse.Namespace) -> None:
    node_names = static_node_names(data)
    keywords = args.media_keywords or ["流媒体", "媒体流"]
    media_count = sum(
        1
        for name in node_names
        if any(keyword.casefold() in name.casefold() for keyword in keywords)
    )
    groups = data.get("proxy-groups", [])
    print(f"output={output}")
    print(f"static_nodes={len(node_names)}")
    print(f"groups={len(groups)}")
    print(f"media_nodes_added={media_count}")
    print(f"default_group={args.manual_group}")
    print(f"auto_group={args.auto_group}")
    print("secrets_printed=false")


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    try:
        if args.command == "export":
            exported = export_source(args.source, args.workdir.expanduser())
            print(f"exported={exported}")
            return 0

        if args.command == "transform":
            input_path = args.input.expanduser().resolve()
            output_path = args.output.expanduser().resolve()
            data = transform_file(args, input_path, output_path)
            print_summary(data, output_path, args)
            return 0

        if args.command == "dry-run":
            input_path = args.input.expanduser().resolve()
            data = load_yaml(input_path)
            keywords = args.media_keywords or ["流媒体", "媒体流"]
            transformed = transform(
                data,
                manual_group=args.manual_group,
                auto_group=args.auto_group,
                disney_group=args.disney_group,
                media_keywords=keywords,
                test_url=args.test_url,
                interval=args.interval,
                tolerance=args.tolerance,
            )
            # Suppress output: dry-run never writes or deploys.
            node_names = static_node_names(data)
            media_count = sum(
                1
                for name in node_names
                if any(keyword.casefold() in name.casefold() for keyword in keywords)
            )
            groups = transformed.get("proxy-groups", [])
            print(f"static_nodes={len(node_names)}")
            print(f"groups={len(groups)}")
            print(f"media_nodes_added={media_count}")
            print(f"default_group={args.manual_group}")
            print(f"auto_group={args.auto_group}")
            print("dry_run=true")
            return 0

        if args.command == "deploy":
            remote = deploy(
                args.file.expanduser().resolve(),
                host=args.host,
                remote_name=args.remote_name,
                core_path=args.core_path,
                activate=args.activate,
            )
            print(f"remote_config={remote}")
            print(f"activated={str(args.activate).lower()}")
            return 0

        if args.command == "all":
            workdir = args.workdir.expanduser().resolve()
            exported = export_source(args.source, workdir)
            output = workdir / args.output_name
            data = transform_file(args, exported, output)
            print(f"source_copy={exported}")
            print_summary(data, output, args)
            if args.deploy:
                remote = deploy(
                    output,
                    host=args.host,
                    remote_name=args.remote_name,
                    core_path=args.core_path,
                    activate=args.activate,
                )
                print(f"remote_config={remote}")
                print(f"activated={str(args.activate).lower()}")
            return 0

        parser.error("Unknown command")
        return 2
    except ConfigError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        print(f"ERROR: command failed with exit code {exc.returncode}", file=sys.stderr)
        return exc.returncode or 1


if __name__ == "__main__":
    raise SystemExit(main())
