#!/usr/bin/env python3
"""Export, transform, validate, and optionally deploy a Clash Verge config for OpenClash.

The transformation is deterministic and idempotent:

- Preserve all static nodes (proxies), specialist groups, DNS, and rules.
- Add global manual/automatic groups with regional fallback ordering.
- Add GPT, Gemini, and Disney specialist groups with regional fallback.
- Gemini explicitly excludes United States nodes.
- Manual-select groups list direct static nodes (no per-node priority wrappers).
- The final MATCH rule routes to the default manual group.
- The `sync` subcommand is a one-shot end-to-end pipeline that accepts "更新 OpenClash 节点"
  as its natural-language trigger.

The script never prints proxy credentials or the full YAML body.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Iterable

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "Missing dependency: PyYAML. Install with: python3 -m pip install PyYAML"
    ) from exc


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_VERGE_CANDIDATES = (
    Path.home()
    / "Library/Application Support/io.github.clash-verge-rev.clash-verge-rev/clash-verge.yaml",
    Path.home()
    / "Library/Application Support/com.github.clash-verge-rev.clash-verge-rev/clash-verge.yaml",
)

FALLBACK_URL = "https://www.gstatic.com/generate_204"
FALLBACK_INTERVAL = 60
FALLBACK_TIMEOUT = 5000
FALLBACK_MAX_FAILED = 1

SYNC_CONFIG_PATH = Path.home() / ".hermes/config/openclash-sync.yaml"

# Skill-generated group names that must be removed on re-generation.
SKILL_GROUP_NAMES: set[str] = {
    "默认代理",
    "手动选择",
    "自动选择",
    "GPT专用",
    "GPT手动",
    "GPT自动",
    "Gemini专用",
    "Gemini手动",
    "Gemini自动",
    "迪士尼",
    "迪士尼手动",
    "迪士尼自动",
}

# Prefixes for wrapper groups generated by this skill.
SKILL_WRAPPER_PREFIXES = ("全局优先│", "GPT优先│", "Gemini优先│", "迪士尼优先│")

# Region keywords – Chinese names and common flag emoji.
REGION_KEYWORDS: dict[str, list[str]] = {
    "日本": ["日本", "\U0001f1ef\U0001f1f5"],  # 🇯🇵
    "台湾": ["台湾", "\U0001f1f9\U0001f1fc"],  # 🇹🇼
    "香港": ["香港", "\U0001f1ed\U0001f1f0"],  # 🇭🇰
    "德国": ["德国", "\U0001f1e9\U0001f1ea"],  # 🇩🇪
    "美国": ["美国", "\U0001f1fa\U0001f1f8"],  # 🇺🇸  – exclusion only
}

# Region display-name → sort key for global / GPT / Disney.
_GLOBAL_REGION_ORDER = {"日本": 0, "台湾": 1}
# Region display-name → sort key for Gemini.
_GEMINI_REGION_ORDER = {"日本": 0, "台湾": 1, "香港": 2, "德国": 3}


# ---------------------------------------------------------------------------
# Sync config template
# ---------------------------------------------------------------------------

SYNC_CONFIG_TEMPLATE = {
    "source": {
        "mode": "clash_verge_effective",
        "effective_config_path": None,
    },
    "router": {
        "host": "root@192.168.10.1",
        "core_path": "/etc/openclash/core/clash_meta",
        "remote_temp_path": "/tmp/clash-verge-static-openclash.yaml",
        "remote_target_path": "/etc/openclash/config/clash-verge-static-openclash.yaml",
    },
    "deployment": {
        "activate_by_default": True,
        "restart_service": True,
        "backup_directory": "/etc/openclash/config/backups",
        "health_wait_seconds": 12,
    },
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


class ConfigError(RuntimeError):
    """Raised when the source configuration cannot be transformed safely."""


def now_stamp() -> str:
    return dt.datetime.now().strftime("%Y%m%d-%H%M%S")


def run(cmd: list[str], *, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        check=check,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )


def find_default_source() -> Path:
    for candidate in DEFAULT_VERGE_CANDIDATES:
        if candidate.is_file():
            return candidate

    base = Path.home() / "Library/Application Support"
    matches = sorted(base.glob("*clash-verge*/**/clash-verge.yaml")) if base.exists() else []
    for match in matches:
        if match.is_file():
            return match

    searched = "\n".join(f"  - {p}" for p in DEFAULT_VERGE_CANDIDATES)
    raise ConfigError(
        "Could not find the Clash Verge effective configuration. Checked:\n"
        f"{searched}\nPass --source explicitly."
    )


def load_yaml(path: Path) -> dict[str, Any]:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise ConfigError(f"Cannot read source file: {path}: {exc}") from exc
    except yaml.YAMLError as exc:
        raise ConfigError(f"Invalid YAML in {path}: {exc}") from exc

    if not isinstance(data, dict):
        raise ConfigError("The YAML root must be a mapping/object.")
    return data


def dump_yaml(data: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = yaml.safe_dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=4096,
    )
    path.write_text(text, encoding="utf-8")


def ordered_unique(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value not in seen:
            result.append(value)
            seen.add(value)
    return result


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# ---------------------------------------------------------------------------
# Sync config
# ---------------------------------------------------------------------------


def load_sync_config() -> dict[str, Any]:
    """Load the sync configuration file. Create a template if it does not exist."""
    cfg_path = SYNC_CONFIG_PATH
    if not cfg_path.is_file():
        cfg_path.parent.mkdir(parents=True, exist_ok=True)
        with open(cfg_path, "w", encoding="utf-8") as f:
            yaml.safe_dump(SYNC_CONFIG_TEMPLATE, f, allow_unicode=True, sort_keys=False, width=4096)
        return dict(SYNC_CONFIG_TEMPLATE)  # deep enough copy for str/list nesting

    try:
        return load_yaml(cfg_path)
    except (ConfigError, yaml.YAMLError) as exc:
        raise ConfigError(f"Invalid sync config {cfg_path}: {exc}") from exc


# ---------------------------------------------------------------------------
# SSH / remote helpers
# ---------------------------------------------------------------------------


def quote_remote(path: str) -> str:
    return shlex.quote(path)


def ssh_command(host: str, command: str, *, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return run(["ssh", host, command], capture=capture)


def check_ssh_batchmode(host: str) -> bool:
    """Return True if SSH BatchMode succeeds for *host*."""
    try:
        run(
            ["ssh", "-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=yes", host, "true"],
            capture=True,
        )
        return True
    except subprocess.CalledProcessError:
        return False


def remote_sha256(host: str, path: str) -> str | None:
    """Return the SHA-256 hex digest of a remote file, or None if the file does not exist."""
    try:
        result = ssh_command(host, f"sha256sum {quote_remote(path)} 2>/dev/null || echo MISSING", capture=True)
        stdout = result.stdout.strip()
        if "MISSING" in stdout:
            return None
        return stdout.split()[0]
    except subprocess.CalledProcessError:
        return None


def remote_file_exists(host: str, path: str) -> bool:
    """Return True if a remote file exists."""
    try:
        ssh_command(host, f"test -f {quote_remote(path)}", capture=True)
        return True
    except subprocess.CalledProcessError:
        return False


def remote_check_file(host: str, path: str) -> None:
    """Raise ConfigError if remote path does not exist."""
    if not remote_file_exists(host, path):
        raise ConfigError(f"Remote path {path} does not exist on {host}")


# ---------------------------------------------------------------------------
# Health check helpers
# ---------------------------------------------------------------------------


def run_health_checks(host: str, health_wait: int) -> dict[str, Any]:
    """Run health checks after OpenClash restart. Returns a dict of check results."""
    import time

    time.sleep(health_wait)

    results: dict[str, Any] = {}

    # 1. Core process
    try:
        pgrep = ssh_command(host, "pgrep -x clash-meta || pgrep -x mihomo || pgrep -x clash || true", capture=True)
        results["core_process"] = bool(pgrep.stdout.strip())
    except subprocess.CalledProcessError:
        results["core_process"] = False

    # 2. Watchdog
    try:
        watchdog = ssh_command(host, "pgrep -f 'openclash.*watchdog' || true", capture=True)
        results["watchdog"] = bool(watchdog.stdout.strip())
    except subprocess.CalledProcessError:
        results["watchdog"] = False

    # 3. Listening port (clash default ports)
    try:
        ports = ssh_command(host, "ss -tlnp | grep -E ':(7890|9090|7891|7892)' || true", capture=True)
        results["listening_ports"] = bool(ports.stdout.strip())
    except subprocess.CalledProcessError:
        results["listening_ports"] = False

    # 4. Startup log
    try:
        logs = ssh_command(
            host,
            "logread -e openclash 2>/dev/null | tail -5 || "
            "journalctl -u openclash -n 5 --no-pager 2>/dev/null || "
            "echo NONE",
            capture=True,
        )
        log_text = logs.stdout.strip()
        results["recent_logs"] = log_text
        results["fatal_error"] = any(
            kw in log_text.lower()
            for kw in ["fatal", "error:", "failed to start", "config error"]
        )
    except subprocess.CalledProcessError:
        results["fatal_error"] = False

    return results


# ---------------------------------------------------------------------------
# Node helpers
# ---------------------------------------------------------------------------


def static_node_names(data: dict[str, Any]) -> list[str]:
    proxies = data.get("proxies")
    if not isinstance(proxies, list) or not proxies:
        raise ConfigError(
            "No static nodes were found under 'proxies:'. Export the Clash Verge effective/merged "
            "configuration rather than a provider-only subscription."
        )

    names: list[str] = []
    for index, proxy in enumerate(proxies):
        if not isinstance(proxy, dict):
            raise ConfigError(f"proxies[{index}] is not an object.")
        name = proxy.get("name")
        if not isinstance(name, str) or not name.strip():
            raise ConfigError(f"proxies[{index}] has no valid name.")
        names.append(name)

    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise ConfigError(f"Duplicate proxy names detected: {', '.join(duplicates)}")
    return names


def detect_region(name: str) -> str | None:
    """Return the canonical region display-name if *name* contains a region keyword."""
    name_lower = name.casefold()
    for region, keywords in REGION_KEYWORDS.items():
        for kw in keywords:
            if kw.casefold() in name_lower:
                return region
    return None


def region_sort_key(name: str, order: dict[str, int]) -> tuple[int, int]:
    """Sort tuple: (region_rank, 0) for recognised regions, (9999, 1) for others."""
    region = detect_region(name)
    if region and region in order:
        return (order[region], 0)
    return (9999, 1)


def _region_order_global_tw_others(name: str) -> tuple[int, int]:
    return region_sort_key(name, _GLOBAL_REGION_ORDER)


def _region_order_gemini(name: str) -> tuple[int, int]:
    return region_sort_key(name, _GEMINI_REGION_ORDER)


def is_skill_group(name: str) -> bool:
    """Return True if *name* is a group generated by this skill."""
    if name in SKILL_GROUP_NAMES:
        return True
    for prefix in SKILL_WRAPPER_PREFIXES:
        if name.startswith(prefix):
            return True
    return False


def is_priority_wrapper(name: str) -> bool:
    """Return True if *name* matches any skill wrapper prefix."""
    return any(name.startswith(p) for p in SKILL_WRAPPER_PREFIXES)


# ---------------------------------------------------------------------------
# Candidate extraction
# ---------------------------------------------------------------------------


def _static_proxies_in_group(
    groups: list[dict[str, Any]], group_name: str, node_names: set[str]
) -> list[str]:
    """Return proxy names in *group_name* that are static nodes."""
    for g in groups:
        if g.get("name") == group_name:
            proxies = g.get("proxies")
            if isinstance(proxies, list):
                return ordered_unique(p for p in proxies if p in node_names)
    return []


def extract_gpt_candidates(
    groups: list[dict[str, Any]], node_names: set[str]
) -> list[str]:
    """GPT candidates from GPT专用 → fallback GPT自动."""
    candidates = _static_proxies_in_group(groups, "GPT专用", node_names)
    if not candidates:
        candidates = _static_proxies_in_group(groups, "GPT自动", node_names)
    return candidates


def extract_gemini_candidates(
    groups: list[dict[str, Any]], node_names: set[str]
) -> list[str]:
    """Gemini candidates: region-filtered (Japan, Taiwan, Hong Kong, Germany, exclude US)."""
    candidates = _static_proxies_in_group(groups, "Gemini专用", node_names)
    if not candidates:
        candidates = _static_proxies_in_group(groups, "Gemini自动", node_names)
    if not candidates:
        candidates = list(node_names)

    allowed_regions = {"日本", "台湾", "香港", "德国"}
    return ordered_unique(
        n for n in candidates if detect_region(n) in allowed_regions
    )


def extract_disney_candidates(
    groups: list[dict[str, Any]],
    node_names: set[str],
    media_keywords: list[str],
) -> list[str]:
    """Disney candidates: original group static nodes + keyword-matched nodes."""
    candidates = _static_proxies_in_group(groups, "迪士尼", node_names)
    if not candidates:
        candidates = _static_proxies_in_group(groups, "迪士尼自动", node_names)

    matched = [
        name
        for name in node_names
        if any(keyword.casefold() in name.casefold() for keyword in media_keywords)
    ]
    result = ordered_unique(list(candidates) + matched)
    return result


# ---------------------------------------------------------------------------
# Group building
# ---------------------------------------------------------------------------


def build_fallback_group(
    name: str,
    proxies: list[str],
    *,
    url: str = FALLBACK_URL,
    interval: int = FALLBACK_INTERVAL,
    timeout: int = FALLBACK_TIMEOUT,
    max_failed_times: int = FALLBACK_MAX_FAILED,
) -> dict[str, Any]:
    return {
        "name": name,
        "type": "fallback",
        "proxies": proxies,
        "url": url,
        "interval": interval,
        "lazy": True,
        "timeout": timeout,
        "max-failed-times": max_failed_times,
    }


def build_select_group(name: str, proxies: list[str]) -> dict[str, Any]:
    return {"name": name, "type": "select", "proxies": proxies}


# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------


def remove_skill_groups(groups: list[dict[str, Any]]) -> None:
    """Remove every group that matches a skill-generated name or prefix."""
    to_remove = [i for i, g in enumerate(groups) if is_skill_group(g.get("name", ""))]
    for i in reversed(to_remove):
        del groups[i]


def remove_old_match_rules(data: dict[str, Any]) -> None:
    """Delete all existing MATCH rules."""
    rules = data.get("rules", [])
    if not isinstance(rules, list):
        raise ConfigError("'rules' must be a list.")
    data["rules"] = [
        r for r in rules if not (isinstance(r, str) and r.strip().upper().startswith("MATCH,"))
    ]


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate_references(data: dict[str, Any], node_names: list[str]) -> None:
    groups = data.get("proxy-groups", [])
    group_names = {
        item.get("name")
        for item in groups
        if isinstance(item, dict) and isinstance(item.get("name"), str)
    }
    valid_targets = set(node_names) | group_names | {"DIRECT", "REJECT", "REJECT-DROP", "PASS"}

    errors: list[str] = []
    for group in groups:
        name = group.get("name", "<unnamed>")
        refs = group.get("proxies", [])
        if refs is None:
            continue
        if not isinstance(refs, list):
            errors.append(f"group '{name}' has a non-list proxies field")
            continue
        for ref in refs:
            if isinstance(ref, str) and ref not in valid_targets:
                errors.append(f"group '{name}' references missing target '{ref}'")

    if errors:
        raise ConfigError("Reference validation failed:\n- " + "\n- ".join(errors))


def check_cycles(groups: list[dict[str, Any]]) -> None:
    """Detect self-references and simple cycles in proxy-groups."""
    group_map: dict[str, list[str]] = {}
    for g in groups:
        name = g.get("name", "")
        refs = g.get("proxies", [])
        if isinstance(name, str) and isinstance(refs, list):
            group_map[name] = [r for r in refs if isinstance(r, str)]

    errors: list[str] = []

    # Self-reference
    for gname, refs in group_map.items():
        if gname in refs:
            errors.append(f"group '{gname}' references itself")

    # Simple two-step cycle
    for gname, refs in group_map.items():
        for r in refs:
            if r in group_map and gname in group_map[r] and gname != r:
                errors.append(f"cycle detected: '{gname}' ↔ '{r}'")

    if errors:
        raise ConfigError("Cycle validation failed:\n- " + "\n- ".join(errors))


def check_unique_group_names(groups: list[dict[str, Any]]) -> None:
    names = [g.get("name", "") for g in groups]
    duplicates = sorted({n for n in names if names.count(n) > 1})
    if duplicates:
        raise ConfigError(f"Duplicate group names: {', '.join(duplicates)}")


def check_node_count(
    data: dict[str, Any], *, min_nodes: int = 1
) -> int:
    """Validate that the config has a reasonable number of static nodes."""
    names = static_node_names(data)
    count = len(names)
    if count < min_nodes:
        raise ConfigError(
            f"Only {count} static node(s) found (minimum required: {min_nodes}). "
            "The Clash Verge effective configuration may not be the merged result."
        )
    return count


def local_validate(data: dict[str, Any]) -> dict[str, Any]:
    """Run all local validation checks and return re-parsed YAML as a round-trip check."""
    node_names = static_node_names(data)
    groups = data.get("proxy-groups", [])
    validate_references(data, node_names)
    check_cycles(groups)
    check_unique_group_names(groups)

    # YAML re-serialisation round-trip
    text = yaml.safe_dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=4096,
    )
    reloaded = yaml.safe_load(text)
    if not isinstance(reloaded, dict):
        raise ConfigError("Output YAML re-serialisation produced a non-dict root.")
    if "proxy-groups" not in reloaded:
        raise ConfigError("Output YAML re-serialisation lost the proxy-groups key.")

    return data


# ---------------------------------------------------------------------------
# Main transform
# ---------------------------------------------------------------------------


def transform(
    data: dict[str, Any],
    *,
    manual_group: str,
    auto_group: str,
    disney_group: str,
    media_keywords: list[str],
    test_url: str = FALLBACK_URL,
    interval: int = FALLBACK_INTERVAL,
    tolerance: int | None = None,
) -> dict[str, Any]:
    node_names = static_node_names(data)
    node_set = set(node_names)
    groups = data.setdefault("proxy-groups", [])
    if not isinstance(groups, list):
        raise ConfigError("'proxy-groups' must be a list.")
    for index, item in enumerate(groups):
        if not isinstance(item, dict):
            raise ConfigError(f"proxy-groups[{index}] is not an object.")

    # --- Extract candidates from existing groups (before cleanup) ---
    global_nodes = node_names  # all static nodes
    gpt_nodes = extract_gpt_candidates(groups, node_set)
    gemini_nodes = extract_gemini_candidates(groups, node_set)
    disney_nodes = extract_disney_candidates(groups, node_set, media_keywords)

    # Sort every candidate list deterministically so wrappers and auto groups
    # follow the same order, guaranteeing idempotency on re-processing.
    global_nodes_sorted = sorted(global_nodes, key=_region_order_global_tw_others)
    gpt_nodes_sorted = sorted(gpt_nodes, key=_region_order_global_tw_others) if gpt_nodes else []
    gemini_nodes_sorted = sorted(gemini_nodes, key=_region_order_gemini) if gemini_nodes else []
    disney_nodes_sorted = sorted(disney_nodes, key=_region_order_global_tw_others) if disney_nodes else []

    # --- Remove old skill groups ---
    remove_skill_groups(groups)
    remove_old_match_rules(data)

    # --- Build groups ---
    # Global (always)
    fallback_url = test_url if test_url != FALLBACK_URL else FALLBACK_URL

    global_auto = build_fallback_group(
        auto_group,
        global_nodes_sorted,
        url=fallback_url,
        interval=interval,
    )
    manual = build_select_group(
        manual_group,
        [auto_group] + global_nodes_sorted,
    )
    default = build_select_group(
        "默认代理",
        [manual_group, auto_group],
    )

    new_groups: list[dict[str, Any]] = [default, manual, global_auto]

    # --- GPT groups (only if candidates exist) ---
    if gpt_nodes_sorted:
        gpt_auto = build_fallback_group(
            "GPT自动",
            gpt_nodes_sorted,
            url=fallback_url,
            interval=interval,
        )
        gpt_manual = build_select_group(
            "GPT手动",
            ["GPT自动"] + gpt_nodes_sorted,
        )
        gpt_special = build_select_group(
            "GPT专用",
            ["GPT手动", "GPT自动"],
        )
        new_groups.extend([gpt_special, gpt_manual, gpt_auto])

    # --- Gemini groups (only if candidates exist) ---
    if gemini_nodes_sorted:
        gemini_auto = build_fallback_group(
            "Gemini自动",
            gemini_nodes_sorted,
            url=fallback_url,
            interval=interval,
        )
        gemini_manual = build_select_group(
            "Gemini手动",
            ["Gemini自动"] + gemini_nodes_sorted,
        )
        gemini_special = build_select_group(
            "Gemini专用",
            ["Gemini手动", "Gemini自动"],
        )
        new_groups.extend([gemini_special, gemini_manual, gemini_auto])

    # --- Disney groups (always generate if there are candidates) ---
    if disney_nodes_sorted:
        disney_auto = build_fallback_group(
            "迪士尼自动",
            disney_nodes_sorted,
            url=fallback_url,
            interval=interval,
        )
        disney_manual = build_select_group(
            "迪士尼手动",
            ["迪士尼自动"] + disney_nodes_sorted,
        )
        disney_special = build_select_group(
            "迪士尼",
            ["迪士尼手动", "迪士尼自动"],
        )
        new_groups.extend([disney_special, disney_manual, disney_auto])

    # --- Replace groups ---
    data["proxy-groups"] = new_groups

    # --- Final MATCH ---
    rules = data.setdefault("rules", [])
    if not isinstance(rules, list):
        raise ConfigError("'rules' must be a list.")
    rules.append("MATCH,默认代理")

    # --- Validate ---
    all_node_names = node_names
    validate_references(data, all_node_names)
    check_cycles(data["proxy-groups"])
    check_unique_group_names(data["proxy-groups"])

    return data


# ---------------------------------------------------------------------------
# Export / Deploy
# ---------------------------------------------------------------------------


def export_source(source: Path | None, workdir: Path) -> Path:
    source = source or find_default_source()
    if not source.is_file():
        raise ConfigError(f"Source does not exist: {source}")
    workdir.mkdir(parents=True, exist_ok=True)
    destination = workdir / f"clash-verge-effective-{now_stamp()}.yaml"
    shutil.copy2(source, destination)
    return destination


def deploy(
    local_file: Path,
    *,
    host: str,
    remote_name: str | None,
    core_path: str,
    activate: bool,
) -> str:
    if not local_file.is_file():
        raise ConfigError(f"Output file does not exist: {local_file}")

    filename = remote_name or local_file.name
    if "/" in filename or filename in {".", ".."}:
        raise ConfigError("--remote-name must be a plain filename.")

    remote_dir = "/etc/openclash/config"
    remote_path = f"{remote_dir}/{filename}"
    stamp = now_stamp()
    remote_backup = f"{remote_path}.bak.{stamp}"
    remote_tmp = f"/tmp/{filename}.upload.{stamp}"

    ssh_command(
        host,
        "set -e; "
        f"mkdir -p {quote_remote(remote_dir)}; "
        f"if [ -f {quote_remote(remote_path)} ]; then cp -p {quote_remote(remote_path)} {quote_remote(remote_backup)}; fi",
    )

    run(["scp", "-O", str(local_file), f"{host}:{remote_tmp}"])

    test_cmd = (
        "set -e; "
        f"chmod 600 {quote_remote(remote_tmp)}; "
        f"{quote_remote(core_path)} -t -d /etc/openclash -f {quote_remote(remote_tmp)}; "
        f"mv -f {quote_remote(remote_tmp)} {quote_remote(remote_path)}; "
        f"chmod 600 {quote_remote(remote_path)}"
    )
    try:
        ssh_command(host, test_cmd)
    except subprocess.CalledProcessError as exc:
        ssh_command(host, f"rm -f {quote_remote(remote_tmp)}", capture=True)
        raise ConfigError("Remote Mihomo validation failed; the active configuration was not changed.") from exc

    if activate:
        activate_cmd = (
            "set -e; "
            "cp -p /etc/config/openclash "
            f"/etc/config/openclash.bak.{stamp}; "
            f"uci set openclash.config.config_path={quote_remote(remote_path)}; "
            "uci set openclash.config.enable='1'; "
            "uci commit openclash; "
            "/etc/init.d/openclash restart"
        )
        ssh_command(host, activate_cmd)

    return remote_path


# ---------------------------------------------------------------------------
# Sync pipeline
# ---------------------------------------------------------------------------


def sync_pipeline(
    config_path: Path | None,
    source_path: Path | None,
    no_activate: bool,
    config_out: Path | None,
) -> dict[str, Any]:
    """Run the full sync pipeline: export → transform → validate → upload → deploy.

    Returns a dict of result metadata suitable for printing.
    """
    result: dict[str, Any] = {
        "input_path": None,
        "input_mtime": None,
        "static_nodes": 0,
        "gpt_candidates": 0,
        "gemini_candidates": 0,
        "disney_candidates": 0,
        "config_sha256": None,
        "local_validated": False,
        "remote_validated": False,
        "replaced": False,
        "restarted": False,
        "rolled_back": False,
        "final_running_config": None,
        "backup_path": None,
        "no_change": False,
        "error": None,
    }

    # 1. Load sync config
    cfg = load_sync_config()
    host = cfg["router"]["host"]
    core_path = cfg["router"]["core_path"]
    remote_target = cfg["router"]["remote_target_path"]
    remote_temp = cfg["router"]["remote_temp_path"]
    backup_dir = cfg["deployment"]["backup_directory"]
    health_wait = cfg["deployment"]["health_wait_seconds"]
    activate = cfg["deployment"]["activate_by_default"] and not no_activate

    # 2. Check SSH BatchMode
    if not check_ssh_batchmode(host):
        raise ConfigError(
            f"BLOCKED_SSH_KEY_REQUIRED\n\n"
            f"SSH BatchMode authentication failed for {host}.\n"
            f"Please configure SSH public-key authentication first:\n\n"
            f"  ssh-copy-id {host}\n\n"
            "Then re-run the sync command. Hermes never prompts for passwords."
        )

    # 3. Find / load source
    source = source_path or find_default_source()
    if not source.is_file():
        raise ConfigError(f"Source file not found: {source}")

    mtime = dt.datetime.fromtimestamp(os.path.getmtime(source), tz=dt.timezone.utc)
    result["input_path"] = str(source)
    result["input_mtime"] = mtime.isoformat()

    data = load_yaml(source)
    node_count = check_node_count(data, min_nodes=1)
    result["static_nodes"] = node_count

    # 4. Transform
    media_keywords = ["流媒体", "媒体流"]
    manual_group = "手动选择"
    auto_group = "自动选择"
    disney_group = "迪士尼"

    transformed = transform(
        data,
        manual_group=manual_group,
        auto_group=auto_group,
        disney_group=disney_group,
        media_keywords=media_keywords,
    )

    # Count candidates
    node_set = set(static_node_names(data))
    groups = transformed.get("proxy-groups", [])
    gpt = extract_gpt_candidates(groups, node_set)
    gemini = extract_gemini_candidates(groups, node_set)
    disney = extract_disney_candidates(groups, node_set, media_keywords)
    result["gpt_candidates"] = len(gpt)
    result["gemini_candidates"] = len(gemini)
    result["disney_candidates"] = len(disney)

    # 5. Local validation
    local_validate(transformed)
    result["local_validated"] = True

    # Write to temp file for upload / SHA-256
    tmp_fd, tmp_path_str = tempfile.mkstemp(suffix=".yaml", prefix="oclash-sync-")
    tmp_path = Path(tmp_path_str)
    os.close(tmp_fd)
    dump_yaml(transformed, tmp_path)
    config_sha = file_sha256(tmp_path)
    result["config_sha256"] = config_sha

    # 6. SHA-256 dedup check
    existing_sha = remote_sha256(host, remote_target)
    if existing_sha == config_sha:
        tmp_path.unlink(missing_ok=True)
        result["no_change"] = True
        result["final_running_config"] = remote_target
        return result

    # 7. Remote pre-checks
    remote_check_file(host, core_path)
    remote_check_file(host, "/etc/openclash/config")

    # 8. Backup existing config
    stamp = now_stamp()
    backup_path = f"{backup_dir}/{Path(remote_target).name}.{stamp}.bak"
    try:
        ssh_command(
            host,
            "set -e; "
            f"mkdir -p {quote_remote(backup_dir)}; "
            f"if [ -f {quote_remote(remote_target)} ]; then "
            f"  cp -p {quote_remote(remote_target)} {quote_remote(backup_path)}; "
            f"fi",
            capture=True,
        )
        result["backup_path"] = backup_path
    except subprocess.CalledProcessError as exc:
        tmp_path.unlink(missing_ok=True)
        raise ConfigError(
            f"Failed to back up remote config: {exc}"
        ) from exc

    if no_activate:
        # --no-activate mode: upload → validate → save (no switch, no restart)
        try:
            run(["scp", "-O", str(tmp_path), f"{host}:{quote_remote(remote_temp)}"])
            ssh_command(
                host,
                "set -e; "
                f"chmod 600 {quote_remote(remote_temp)}; "
                f"{quote_remote(core_path)} -t -d /etc/openclash -f {quote_remote(remote_temp)}; "
                f"mv -f {quote_remote(remote_temp)} {quote_remote(remote_target)}; "
                f"chmod 600 {quote_remote(remote_target)}",
            )
            result["remote_validated"] = True
            result["replaced"] = True
            result["final_running_config"] = remote_target
            result["restarted"] = False
        except subprocess.CalledProcessError as exc:
            ssh_command(host, f"rm -f {quote_remote(remote_temp)}", capture=True)
            tmp_path.unlink(missing_ok=True)
            raise ConfigError(f"No-activate sync failed during upload or validation: {exc}") from exc

        tmp_path.unlink(missing_ok=True)
        return result

    # 9. Full sync: upload
    try:
        run(["scp", "-O", str(tmp_path), f"{host}:{quote_remote(remote_temp)}"])
    except subprocess.CalledProcessError as exc:
        tmp_path.unlink(missing_ok=True)
        raise ConfigError(f"SCP upload failed: {exc}") from exc

    # 10. Remote core validation
    try:
        ssh_command(
            host,
            "set -e; "
            f"chmod 600 {quote_remote(remote_temp)}; "
            f"{quote_remote(core_path)} -t -d /etc/openclash -f {quote_remote(remote_temp)}",
            capture=True,
        )
        result["remote_validated"] = True
    except subprocess.CalledProcessError as exc:
        ssh_command(host, f"rm -f {quote_remote(remote_temp)}", capture=True)
        tmp_path.unlink(missing_ok=True)
        raise ConfigError("Remote Mihomo validation failed; the active configuration was not changed.") from exc

    # 11. Atomic replace
    try:
        ssh_command(
            host,
            "set -e; "
            f"mv -f {quote_remote(remote_temp)} {quote_remote(remote_target)}; "
            f"chmod 600 {quote_remote(remote_target)}",
        )
        result["replaced"] = True
    except subprocess.CalledProcessError as exc:
        ssh_command(host, f"rm -f {quote_remote(remote_temp)}", capture=True)
        tmp_path.unlink(missing_ok=True)
        raise ConfigError(f"Atomic replace failed: {exc}") from exc

    # 12. Restart OpenClash
    if activate:
        try:
            ssh_command(host, "/etc/init.d/openclash restart", capture=True)
            result["restarted"] = True
        except subprocess.CalledProcessError as exc:
            # Restart itself failed — rollback
            _rollback_and_report(host, backup_path, remote_target, backup_dir, health_wait, result)
            tmp_path.unlink(missing_ok=True)
            raise ConfigError(f"OpenClash restart failed: {exc}") from exc

        # 13. Health check
        health = run_health_checks(host, health_wait)

        if not health.get("core_process"):
            # Core not running — rollback
            _rollback_and_report(host, backup_path, remote_target, backup_dir, health_wait, result)
            tmp_path.unlink(missing_ok=True)
            raise ConfigError("Health check failed: core process not running after restart. Rollback applied.")

        if health.get("fatal_error"):
            _rollback_and_report(host, backup_path, remote_target, backup_dir, health_wait, result)
            tmp_path.unlink(missing_ok=True)
            raise ConfigError("Health check failed: fatal error in OpenClash logs. Rollback applied.")

    tmp_path.unlink(missing_ok=True)
    result["final_running_config"] = remote_target
    return result


def _rollback_and_report(
    host: str,
    backup_path: str,
    remote_target: str,
    backup_dir: str,
    health_wait: int,
    result: dict[str, Any],
) -> None:
    """Restore the backup config and restart OpenClash."""
    try:
        # Check if backup exists
        exists = remote_file_exists(host, backup_path)
        if exists:
            ssh_command(
                host,
                "set -e; "
                f"cp -p {quote_remote(backup_path)} {quote_remote(remote_target)}; "
                "/etc/init.d/openclash restart",
                capture=True,
            )
            result["rolled_back"] = True
            result["final_running_config"] = remote_target

            # Brief health re-check after rollback
            import time
            time.sleep(health_wait)
            rb_health = run_health_checks(host, health_wait)
            if not rb_health.get("core_process"):
                result["final_running_config"] = f"{remote_target} (rollback applied but core not verified)"
        else:
            result["rolled_back"] = False
            result["final_running_config"] = f"{remote_target} (backup not found at {backup_path})"

    except subprocess.CalledProcessError:
        result["rolled_back"] = False
        result["final_running_config"] = f"{remote_target} (rollback attempted but failed)"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert a Clash Verge effective YAML into a static OpenClash configuration."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    export_p = sub.add_parser("export", help="Copy the current Clash Verge effective YAML to a work directory.")
    export_p.add_argument("--source", type=Path)
    export_p.add_argument("--workdir", type=Path, default=Path.home() / "Desktop/openclash-static-work")

    transform_p = sub.add_parser("transform", help="Transform an exported/effective YAML.")
    transform_p.add_argument("--input", type=Path, required=True)
    transform_p.add_argument("--output", type=Path, required=True)
    add_transform_args(transform_p)

    all_p = sub.add_parser("all", help="Export, transform, and optionally deploy in one command.")
    all_p.add_argument("--source", type=Path)
    all_p.add_argument("--workdir", type=Path, default=Path.home() / "Desktop/openclash-static-work")
    all_p.add_argument("--output-name", default="clash-verge-static-openclash.yaml")
    add_transform_args(all_p)
    add_deploy_args(all_p)

    deploy_p = sub.add_parser("deploy", help="Upload an existing YAML and validate it remotely before installation.")
    deploy_p.add_argument("--file", type=Path, required=True)
    add_deploy_args(deploy_p)

    dry_run_p = sub.add_parser("dry-run", help="Transform without writing output, deploying, or SSH.")
    dry_run_p.add_argument("--input", type=Path, required=True)
    add_transform_args(dry_run_p)

    sync_p = sub.add_parser(
        "sync",
        help=(
            "End-to-end: export from Clash Verge, transform, locally validate, compute SHA-256, "
            "upload (if changed), remote-validate, replace, restart, and health-check. "
            "Natural-language trigger: 更新 OpenClash 节点."
        ),
    )
    sync_p.add_argument("--source", type=Path, help="Override the Clash Verge effective YAML path.")
    sync_p.add_argument(
        "--config", type=Path, default=SYNC_CONFIG_PATH,
        help=f"Sync configuration file (default: {SYNC_CONFIG_PATH}).",
    )
    sync_p.add_argument(
        "--no-activate",
        action="store_true",
        help="Upload, validate, and save the config, but do NOT switch the active config or restart OpenClash.",
    )
    sync_p.add_argument(
        "--config-out", type=Path,
        help="Also write the transformed config to a local path for inspection.",
    )

    return parser


def add_transform_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--manual-group", default="手动选择")
    parser.add_argument("--auto-group", default="自动选择")
    parser.add_argument("--disney-group", default="迪士尼")
    parser.add_argument(
        "--media-keyword",
        action="append",
        dest="media_keywords",
        help="Node-name keyword added to the Disney group. Repeatable. Defaults: 流媒体, 媒体流.",
    )
    parser.add_argument("--test-url", default=FALLBACK_URL)
    parser.add_argument("--interval", type=int, default=FALLBACK_INTERVAL)
    parser.add_argument("--tolerance", type=int, default=None)


def add_deploy_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--deploy", action="store_true", help="For 'all': upload after transformation.")
    parser.add_argument("--host", default="root@192.168.10.1")
    parser.add_argument("--remote-name")
    parser.add_argument("--core-path", default="/etc/openclash/core/clash_meta")
    parser.add_argument(
        "--activate",
        action="store_true",
        help="After remote validation, select this config through UCI and restart OpenClash. Opt-in only.",
    )


def transform_file(args: argparse.Namespace, input_path: Path, output_path: Path) -> dict[str, Any]:
    data = load_yaml(input_path)
    keywords = args.media_keywords or ["流媒体", "媒体流"]
    transformed = transform(
        data,
        manual_group=args.manual_group,
        auto_group=args.auto_group,
        disney_group=args.disney_group,
        media_keywords=keywords,
        test_url=args.test_url,
        interval=args.interval,
        tolerance=args.tolerance,
    )
    dump_yaml(transformed, output_path)
    return transformed


def print_summary(data: dict[str, Any], output: Path, args: argparse.Namespace) -> None:
    node_names = static_node_names(data)
    keywords = args.media_keywords or ["流媒体", "媒体流"]
    media_count = sum(
        1
        for name in node_names
        if any(keyword.casefold() in name.casefold() for keyword in keywords)
    )
    groups = data.get("proxy-groups", [])
    print(f"output={output}")
    print(f"static_nodes={len(node_names)}")
    print(f"groups={len(groups)}")
    print(f"media_nodes_added={media_count}")
    print(f"default_group={args.manual_group}")
    print(f"auto_group={args.auto_group}")
    print("secrets_printed=false")


def print_sync_report(result: dict[str, Any]) -> None:
    """Print the sync result as deterministic key=value lines (no secrets)."""
    for key in (
        "input_path",
        "input_mtime",
        "static_nodes",
        "gpt_candidates",
        "gemini_candidates",
        "disney_candidates",
        "config_sha256",
        "local_validated",
        "remote_validated",
        "replaced",
        "restarted",
        "rolled_back",
        "final_running_config",
        "backup_path",
        "no_change",
    ):
        val = result.get(key)
        if val is None:
            print(f"{key}=None")
        elif isinstance(val, bool):
            print(f"{key}={str(val).lower()}")
        else:
            print(f"{key}={val}")


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    try:
        if args.command == "sync":
            result = sync_pipeline(
                config_path=args.config,
                source_path=args.source,
                no_activate=args.no_activate,
                config_out=args.config_out,
            )

            # Also write local copy if requested
            if args.config_out and result.get("config_sha256"):
                if result.get("no_change"):
                    print(f"local_output=skipped (no change)")
                else:
                    tmp_fd, tmp_path_str = tempfile.mkstemp(suffix=".yaml", prefix="oclash-sync-out-")
                    os.close(tmp_fd)
                    tmp_p = Path(tmp_path_str)
                    data = load_yaml(Path(result["input_path"]))
                    media_keywords = ["流媒体", "媒体流"]
                    transformed = transform(
                        data,
                        manual_group="手动选择",
                        auto_group="自动选择",
                        disney_group="迪士尼",
                        media_keywords=media_keywords,
                    )
                    dump_yaml(transformed, args.config_out.expanduser().resolve())
                    print(f"local_output={args.config_out}")

            print_sync_report(result)

            if result.get("no_change"):
                print("NO_CHANGE_OPENCLASH_CONFIG_CURRENT")
                return 0

            if result.get("rolled_back"):
                print("STATUS=ROLLED_BACK")
            elif result.get("restarted"):
                print("STATUS=ACTIVATED")
            elif result.get("replaced"):
                print("STATUS=REPLACED_NO_ACTIVATE")
            else:
                print("STATUS=OK")

            return 0

        if args.command == "export":
            exported = export_source(args.source, args.workdir.expanduser())
            print(f"exported={exported}")
            return 0

        if args.command == "transform":
            input_path = args.input.expanduser().resolve()
            output_path = args.output.expanduser().resolve()
            data = transform_file(args, input_path, output_path)
            print_summary(data, output_path, args)
            return 0

        if args.command == "dry-run":
            input_path = args.input.expanduser().resolve()
            data = load_yaml(input_path)
            keywords = args.media_keywords or ["流媒体", "媒体流"]
            transformed = transform(
                data,
                manual_group=args.manual_group,
                auto_group=args.auto_group,
                disney_group=args.disney_group,
                media_keywords=keywords,
                test_url=args.test_url,
                interval=args.interval,
                tolerance=args.tolerance,
            )
            # Suppress output: dry-run never writes or deploys.
            node_names = static_node_names(data)
            media_count = sum(
                1
                for name in node_names
                if any(keyword.casefold() in name.casefold() for keyword in keywords)
            )
            groups = transformed.get("proxy-groups", [])
            print(f"static_nodes={len(node_names)}")
            print(f"groups={len(groups)}")
            print(f"media_nodes_added={media_count}")
            print(f"default_group={args.manual_group}")
            print(f"auto_group={args.auto_group}")
            print("dry_run=true")
            return 0

        if args.command == "deploy":
            remote = deploy(
                args.file.expanduser().resolve(),
                host=args.host,
                remote_name=args.remote_name,
                core_path=args.core_path,
                activate=args.activate,
            )
            print(f"remote_config={remote}")
            print(f"activated={str(args.activate).lower()}")
            return 0

        if args.command == "all":
            workdir = args.workdir.expanduser().resolve()
            exported = export_source(args.source, workdir)
            output = workdir / args.output_name
            data = transform_file(args, exported, output)
            print(f"source_copy={exported}")
            print_summary(data, output, args)
            if args.deploy:
                remote = deploy(
                    output,
                    host=args.host,
                    remote_name=args.remote_name,
                    core_path=args.core_path,
                    activate=args.activate,
                )
                print(f"remote_config={remote}")
                print(f"activated={str(args.activate).lower()}")
            return 0

        parser.error("Unknown command")
        return 2

    except ConfigError as exc:
        msg = str(exc)
        if msg.startswith("BLOCKED_SSH_KEY_REQUIRED"):
            # Print the BLOCKED message to stderr for the caller to detect
            print(msg, file=sys.stderr)
        else:
            print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        print(f"ERROR: command failed with exit code {exc.returncode}", file=sys.stderr)
        return exc.returncode or 1


if __name__ == "__main__":
    raise SystemExit(main())
